export const GET_MOVIES = "GET_MOVIES";
export const MOVIES_LOADING = "MOVIES_LOADING";
export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";
export const GET_NOMINATIONS = "GET_NOMINATIONS";
export const NOMINATIONS_LOADING = "NOMINATIONS_LOADING";
